#ifndef LIBFUSE_CONFIG_H
#define LIBFUSE_CONFIG_H

#define FUSE_MAJOR_VERSION 3
#define FUSE_MINOR_VERSION 18
#define FUSE_HOTFIX_VERSION 0
#define FUSE_USE_VERSION 318

#endif /* LIBFUSE_CONFIG_H */
